--Tạo CSDL
CREATE DATABASE QUANLYBENHVIENN
USE QUANLYBENHVIENN

--Tạo tài khoản
CREATE TABLE TAIKHOAN
(
	TENDN		NVARCHAR (20) CONSTRAINT PK_TAIKHOAN PRIMARY KEY(TENDN),
	MATKHAU		VARCHAR (50),
	TENTK		NVARCHAR(50)
)

--KHOA
CREATE TABLE KHOA
(
	MAKHOA		NVARCHAR(6) CONSTRAINT PK_KHOA PRIMARY KEY(MAKHOA),
	TENKHOA		NVARCHAR(50),
	SDTKHOA		NVARCHAR(10)
)

--PHÒNG CHỨC NĂNG
CREATE TABLE PHONGCHUCNANG
(
	MAPH		NVARCHAR(6) CONSTRAINT PK_PHONGCHUCNANG PRIMARY KEY(MAPH),
	TENPH		NVARCHAR(50),
	SDTPH		NVARCHAR(10)
)

--CHỨC VỤ
CREATE TABLE CHUCVU
(
	MACV		NVARCHAR(6) CONSTRAINT PK_CHUCVU PRIMARY KEY(MACV),
	TENCV		NVARCHAR(50)
)

--ĐỐI TƯỢNG
CREATE TABLE DOITUONG
(
	MADT		NVARCHAR(6) CONSTRAINT PK_DOITUONG PRIMARY KEY(MADT),
	TENDT		NVARCHAR(100),
	MIENGIAM	FLOAT,
	DIEUKIEN	NVARCHAR(100)
)

--NHÂN VIÊN
CREATE TABLE NHANVIEN
(
	MANV		NVARCHAR(6) CONSTRAINT PK_NHANVIEN		PRIMARY KEY(MANV),
	MAPH		NVARCHAR(6) CONSTRAINT FK_NHANVIEN_MAPH FOREIGN KEY(MAPH) REFERENCES PHONGCHUCNANG(MAPH),
	MACV		NVARCHAR(6) CONSTRAINT FK_NHANVIEN_MACV FOREIGN KEY(MACV) REFERENCES CHUCVU(MACV),
	HOTENNV		NVARCHAR(100),
	GIOITINHNV	NVARCHAR(10) CONSTRAINT CK_GIOITINHNV_NHANVIEN CHECK (GIOITINHNV IN (N'Nam', N'Nữ', N'Khác')),
	CMNDNV		NVARCHAR(12),
	DIACHINV	NVARCHAR(100),
	NGAYSINHNV	DATETIME,
	SDTNV		NVARCHAR(10),
	EMAILNV		NVARCHAR(50),
	LUONGNV		FLOAT
)

--BÁC SĨ
CREATE TABLE BACSI
(
	MABS		NVARCHAR(6) CONSTRAINT PK_BACSI		   PRIMARY KEY(MABS),
	MAKHOA		NVARCHAR(6) CONSTRAINT FK_BACSI_MAKHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA),
	MACV		NVARCHAR(6) CONSTRAINT FK_BACSI_MACV   FOREIGN KEY(MACV)   REFERENCES CHUCVU(MACV),
	HOTENBS		NVARCHAR(100),
	GIOITINHBS	NVARCHAR(10) CONSTRAINT CK_GIOITINHBS_BACSI CHECK (GIOITINHBS IN (N'Nam', N'Nữ', N'Khác')),
	CMNDBS		NVARCHAR(12),
	DIACHIBS	NVARCHAR(100),
	NGAYSINHBS	DATETIME,
	SDTBS		NVARCHAR(10),
	LUONGBS		FLOAT
)

--Y TÁ
CREATE TABLE YTA
(
	MAYT		NVARCHAR(6) CONSTRAINT PK_YTA		 PRIMARY KEY(MAYT),
	MAKHOA		NVARCHAR(6) CONSTRAINT FK_YTA_MAKHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA),
	MACV		NVARCHAR(6) CONSTRAINT FK_YTA_MACV	 FOREIGN KEY(MACV)	 REFERENCES CHUCVU(MACV),
	HOTENYT		NVARCHAR(100),
	GIOITINHYT	NVARCHAR(10) CONSTRAINT CK_GIOITINHYT_YTA CHECK (GIOITINHYT IN (N'Nam', N'Nữ', N'Khác')),
	CMNDYT		NVARCHAR(12),
	DIACHIYT	NVARCHAR(100),
	NGAYSINHYT	DATETIME,
	SDTYT		NVARCHAR(10),
	LUONGYT		FLOAT
)

--NHÀ CUNG CẤP
CREATE TABLE NHACUNGCAP
(
	MANCC		NVARCHAR(6) CONSTRAINT PK_NHACUNGCAP PRIMARY KEY(MANCC),
	TENNCC		NVARCHAR(100),
	DIACHI		NVARCHAR(100),
	SDT			NVARCHAR(10),
	EMAIL		NVARCHAR(50),
	WEBSITE		NVARCHAR(100)
)

--HỒ SƠ THUỐC 
CREATE TABLE HOSOTHUOC
(
	MATHUOC		NVARCHAR(6) CONSTRAINT PK_HOSOTHUOC		  PRIMARY KEY(MATHUOC),
	MANCC		NVARCHAR(6) CONSTRAINT FK_HOSOTHUOC_MANCC FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP(MANCC),
	TENTHUOC	NVARCHAR(50),
	NGAYSX		DATETIME,
	NGAYHETHAN	DATETIME,
	NGAYMUA		DATETIME,
	SLTHUOC		INTEGER,
	DVT			NVARCHAR(20),
	DGNHAP		FLOAT
)

--HỒ SƠ BỆNH ÁN
CREATE TABLE HOSOBENHAN
(
	MAHS				NVARCHAR(6) CONSTRAINT PK_HOSOBENHAN		PRIMARY KEY(MAHS),
	MABN				NVARCHAR(6) CONSTRAINT FK_HOSOBENHAN_MABN FOREIGN KEY(MABN) REFERENCES BENHNHAN(MABN),
	MAKHOA				NVARCHAR(6) CONSTRAINT FK_HOSOBENHAN_MAKHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA),
	MAPDT				NVARCHAR(6) CONSTRAINT FK_HOSOBENHAN_MAPDT	FOREIGN KEY(MAPDT) REFERENCES PHIEUDIEUTRI(MAPDT),
	PHUONGPHAPDIEUTRI	NVARCHAR(100),
	PHANUNGPHU			NVARCHAR(50),
	KETQUA				NVARCHAR(50)
)
--BỆNH NHÂN
CREATE TABLE BENHNHAN
(
	MABN		NVARCHAR(6) CONSTRAINT PK_BENHNHAN		PRIMARY KEY(MABN),
	MADT		NVARCHAR(6) CONSTRAINT FK_BENHNHAN_MADT FOREIGN KEY(MADT) REFERENCES DOITUONG(MADT),
	HOTENBN     NVARCHAR(100),
	GIOITINHBN	NVARCHAR(10) CONSTRAINT CK_GIOITINHBN_BENHNHAN CHECK (GIOITINHBN IN (N'Nam', N'Nữ', N'Khác')),
	CMNDBN		NVARCHAR(12),
	DIACHIBN	NVARCHAR(100),
	NGAYSINHBN	DATETIME,
	SDTBN		NVARCHAR(10),
	EMAILBN		NVARCHAR(50)
)

--PHIẾU ĐIỀU TRỊ
CREATE TABLE PHIEUDIEUTRI
(
	MAPDT		NVARCHAR(6) CONSTRAINT PK_PHIEUDIEUTRI		PRIMARY KEY(MAPDT),
	MABN		NVARCHAR(6) CONSTRAINT FK_PHIEUDIEUTRI_MABN FOREIGN KEY(MABN) REFERENCES BENHNHAN (MABN),	
	NGAYKHAM	DATETIME,
	MOTA		NTEXT,
	KETLUAN		NTEXT
)

--TOA THUỐC
CREATE TABLE TOATHUOC
(
	MAPDT		NVARCHAR(6) CONSTRAINT FK_TOATHUOC_MAPDT	FOREIGN KEY(MAPDT)	 REFERENCES PHIEUDIEUTRI(MAPDT),
	MABN		NVARCHAR(6) CONSTRAINT FK_TOATHUOC_MABN		FOREIGN KEY(MABN)	 REFERENCES BENHNHAN(MABN),
	MABS		NVARCHAR(6) CONSTRAINT FK_TOATHUOC_MABS		FOREIGN KEY(MABS)	 REFERENCES BACSI(MABS),
	MATHUOC		NVARCHAR(6) CONSTRAINT FK_TOATHUOC_MATHUOC	FOREIGN KEY(MATHUOC) REFERENCES HOSOTHUOC(MATHUOC),
	CONSTRAINT PK_TOATHUOC PRIMARY KEY (MAPDT, MABN, MABS, MATHUOC),
	SOLAN		INTEGER,
	LIEULUONG	NVARCHAR(20)
)

--HÓA ĐƠN VIỆN PHÍ
CREATE TABLE HOADONVIENPHI
(
	MAHD		 NVARCHAR(6) CONSTRAINT PK_HOADONVIENPHI	  PRIMARY KEY(MAHD),
	MABN		 NVARCHAR(6) CONSTRAINT FK_HOADONVIENPHI_MABN FOREIGN KEY(MABN) REFERENCES BENHNHAN(MABN),
	MANV		 NVARCHAR(6) CONSTRAINT FK_HOADONVIENPHI_MANV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	NGAYKHAM	 DATETIME,
	NGAYLAYTHUOC DATETIME,
	HTTT		 NVARCHAR(20),
	THANHTIEN    FLOAT
)

--CHI TIẾT HÓA ĐƠN VIỆN PHÍ
CREATE TABLE CHITIETHOADON
(
	MAHD		NVARCHAR(6) CONSTRAINT FK_CTHD_MAHD	   FOREIGN KEY(MAHD)	REFERENCES HOADONVIENPHI(MAHD),
	MATHUOC		NVARCHAR(6) CONSTRAINT FK_CTHD_MATHUOC FOREIGN KEY(MATHUOC) REFERENCES HOSOTHUOC(MATHUOC),
	CONSTRAINT PK_CHITIETHOADON PRIMARY KEY (MAHD, MATHUOC),
	SOLUONG		INT,
	DGBAN		FLOAT
)

--BÁO CÁO
CREATE TABLE BAOCAO
(
	MABC NVARCHAR(6) CONSTRAINT PK_BAOCAO	    PRIMARY KEY(MABC),
	MANV NVARCHAR(6) CONSTRAINT FK_BAOCAO_MANV  FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	TENBC NVARCHAR(100),
	NGAYLAP DATETIME,
	CHUTHICH NVARCHAR(100)
)
